"""build-target-profiles.py — regenerate src/data/target-profiles.js from pyfa's builtins.

    python scripts/build-target-profiles.py [--dry-run]

TARGET RESIST profiles are the mirror image of the incoming damage profiles in
damage-profiles.js: those say what damage types are hitting YOU (and weight EHP), these say how
resistant the thing you are SHOOTING is (and weight outgoing DPS). Both come from pyfa so the two
apps agree on the reference numbers.

Source of truth is `BUILTINS` in Pyfa-master/eos/saveddata/targetProfile.py, an OrderedDict of
    id -> (name, emResist, thermalResist, kineticResist, explosiveResist)
where each resist is a FRACTION (0.25 = 25% resistant). pyfa builds its names from two helpers,
`_t(x) -> x` and `_c(x) -> '[' + x + ']'`, so a bracketed leading segment is a category label —
which is exactly the grouping this file emits.

Parsed with a regex rather than importing the module: importing it drags in eos.db, sqlalchemy and
logbook for what is a flat table of literals.
"""
import os
import re
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SRC = os.path.join(ROOT, 'Pyfa-master', 'eos', 'saveddata', 'targetProfile.py')
OUT = os.path.join(ROOT, 'src', 'data', 'target-profiles.js')

# (-19, (_c(_t('NPC')) + _c(_t('Asteroid')) + _t('Angel Cartel'), 0.54, 0.42, 0.37, 0.32)),
#
# Entries are NOT a fixed width: the Burner profiles carry three extra fields after the resists
# (maxVelocity, signatureRadius, radius) which pyfa uses for its burner-specific application maths
# and we ignore. Matching a fixed four numbers silently picked up the LAST four on those lines —
# an Enyo came out as [0.235, 1020, 37, 39]. So capture the whole numeric tail and take the first
# four, which are the resists in every variant.
ENTRY = re.compile(
    r"\(\s*-?\d+\s*,\s*\(\s*(?P<name>.+?)(?P<nums>(?:\s*,\s*-?[\d.]+)+)\s*\)\s*\)",
    re.S)
# Category segments are _c WRAPPING _t — `_c(_t('NPC'))` — so the two cannot be told apart by
# matching them independently; the _c( prefix has to be part of the same match.
PART = re.compile(r"(?P<cat>_c\(\s*)?_t\(\s*'(?P<s>[^']*)'\s*\)")


def parse_name(expr):
    """'_c(_t("NPC")) + _c(_t("Asteroid")) + _t("Angel Cartel")' -> ('NPC / Asteroid', 'Angel Cartel')."""
    cats, leaf = [], []
    for m in PART.finditer(expr):
        (cats if m.group('cat') else leaf).append(m.group('s'))
    return ' / '.join(cats) if cats else 'Generic', ' '.join(leaf).strip() or '(unnamed)'


def main():
    dry = '--dry-run' in sys.argv
    if not os.path.isfile(SRC):
        sys.exit(f"pyfa source not found at {SRC} — clone it (see CLAUDE.md) or pass a different root.")
    text = open(SRC, encoding='utf-8').read()
    i = text.index('BUILTINS = OrderedDict([')
    # The dict closes as `...))])` on the SAME line as its last entry, not on a line of its own —
    # so anchor on the blank line before the next top-level statement instead of a literal '\n])'.
    block = text[i:text.index('\n\n', i)]

    groups, order = {}, []
    skipped = 0
    for m in ENTRY.finditer(block):
        cat, name = parse_name(m.group('name'))
        nums = [float(x) for x in m.group('nums').strip().lstrip(',').split(',')]
        if len(nums) < 4:
            skipped += 1
            continue
        # pyfa stores resists as fractions; keep them that way so calc.js can multiply directly.
        row = (name, *nums[:4])
        if any(not (0 <= v <= 1) for v in nums[:4]):
            sys.exit(f"resist out of range for {cat} / {name}: {nums[:4]} — the entry shape changed, "
                     f"check targetProfile.py before regenerating.")
        if cat not in groups:
            groups[cat] = []
            order.append(cat)
        groups[cat].append(row)

    total = sum(len(v) for v in groups.values())
    print(f"parsed {total} target profiles in {len(order)} categories")
    for c in order:
        print(f"   {len(groups[c]):3}  {c}")

    lines = [
        "// Auto-generated by scripts/build-target-profiles.py from pyfa's builtin target profiles",
        "// (eos/saveddata/targetProfile.py). Do not hand-edit — regenerate instead.",
        "//",
        "// r=[em,th,kin,exp] RESIST fractions of the thing you are shooting (0.25 = 25% resistant),",
        "// used to weight outgoing DPS. This is the counterpart to DAMAGE_PROFILES, which describes",
        "// incoming damage types and weights EHP.",
        "export const TARGET_PROFILES = [",
    ]
    # "None" is not in pyfa's table — pyfa models it as target profile id 0, composed at runtime.
    # Prepend it to the group it belongs with rather than emitting a second "Generic" heading.
    groups.setdefault('Generic', [])
    if 'Generic' not in order:
        order.insert(0, 'Generic')
    groups['Generic'].insert(0, ('None (0%)', 0, 0, 0, 0))
    for c in order:
        items = ','.join(
            '{{n:"{}",r:[{},{},{},{}]}}'.format(n.replace('"', '\\"'), em, th, kin, ex)
            for (n, em, th, kin, ex) in groups[c])
        lines.append(f'  {{cat:"{c}",items:[{items}]}},')
    lines.append('];')
    out = '\n'.join(lines) + '\n'

    if dry:
        print(f"\n--dry-run: would write {len(out):,} bytes to {OUT}")
        return
    with open(OUT, 'w', encoding='utf-8', newline='\n') as fh:
        fh.write(out)
    print(f"\nwrote {OUT}  ({len(out):,} bytes)")


if __name__ == '__main__':
    main()
